site_name: Documentação de Requisitos
site_description: Documentação de requisitos de software para o projeto web
site_author: Seu Projeto

theme:
  name: material
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: dark
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Modo claro
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - offline

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      toc_depth: 2

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Documento de visao:
      - Introdução: documento-visao/introducao.md
      - teste: documento-visao/testes.md
  # - Especificação:
  #     - Casos de Uso: especificacao/casos-uso.md
  #     - Arquitetura: especificacao/arquitetura.md
  # - Documentação:
  #     - Glossário: documentacao/glossario.md
  #     - FAQ: documentacao/faq.md